# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058020c45f495419457fd3b8dfaa756fdba5a3c5569585ce3ab3373a2dceeaac383308de84533e944dc7dba6496e03633e24f0e51d99a54b2654e797ed8813b9

test:
  secret_key_base: 682598d6f0d12b1d80a37cc86e06d5def5b6a0cc020f36382e018ffa0512239b8aced1a3817086da8f51d9628f3e508405d6834869b77f2065f26eb249a8fedb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
